{
  "id": 37728610193,
  "guid": "be8a2120-09b8-11ee-88f6-3456e4efc730",
  "delivered_at": "2023-06-13T07:05:58Z",
  "redelivery": false,
  "duration": 0.29,
  "status": "502 Bad Gateway",
  "status_code": 502,
  "event": "issue_comment",
  "action": "created",
  "installation_id": null,
  "repository_id": 639498256,
  "url": "https://sfdc.rocks",
  "request": {
    "headers": {
      "Accept": "*/*",
      "User-Agent": "GitHub-Hookshot/9a41b9d",
      "X-GitHub-Delivery": "be8a2120-09b8-11ee-88f6-3456e4efc730",
      "X-GitHub-Event": "issue_comment",
      "X-GitHub-Hook-ID": "419264307",
      "X-GitHub-Hook-Installation-Target-ID": "80924672",
      "X-GitHub-Hook-Installation-Target-Type": "organization",
      "content-type": "application/json"
    },
    "payload": {
      "action": "created",
      "issue": {
        "url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245",
        "repository_url": "https://api.github.com/repos/casa-vega/issue-ops",
        "labels_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245/labels{/name}",
        "comments_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245/comments",
        "events_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245/events",
        "html_url": "https://github.com/casa-vega/issue-ops/issues/245",
        "id": 1754188030,
        "node_id": "I_kwDOJh34EM5ojsj-",
        "number": 245,
        "title": "[org-get-webhook-delivery] get a webhook delivery",
        "user": {
          "login": "cvega",
          "id": 376532,
          "node_id": "MDQ6VXNlcjM3NjUzMg==",
          "avatar_url": "https://avatars.githubusercontent.com/u/376532?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cvega",
          "html_url": "https://github.com/cvega",
          "followers_url": "https://api.github.com/users/cvega/followers",
          "following_url": "https://api.github.com/users/cvega/following{/other_user}",
          "gists_url": "https://api.github.com/users/cvega/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cvega/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cvega/subscriptions",
          "organizations_url": "https://api.github.com/users/cvega/orgs",
          "repos_url": "https://api.github.com/users/cvega/repos",
          "events_url": "https://api.github.com/users/cvega/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cvega/received_events",
          "type": "User",
          "site_admin": true
        },
        "labels": [
          {
            "id": 5575895611,
            "node_id": "LA_kwDOJh34EM8AAAABTFlqOw",
            "url": "https://api.github.com/repos/casa-vega/issue-ops/labels/org-get-webhook-delivery",
            "name": "org-get-webhook-delivery",
            "color": "7C3FB5",
            "default": false,
            "description": null
          }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2023-06-13T07:05:09Z",
        "updated_at": "2023-06-13T07:05:57Z",
        "closed_at": "2023-06-13T07:05:27Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "body": "### GitHub Organization (*)casa-vega### Webhook URL (*)https://sfdc.rocks",
        "reactions": {
          "url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245/reactions",
          "total_count": 0,
          "+1": 0,
          "-1": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245/timeline",
        "performed_via_github_app": null,
        "state_reason": "completed"
      },
      "comment": {
        "url": "https://api.github.com/repos/casa-vega/issue-ops/issues/comments/1588672334",
        "html_url": "https://github.com/casa-vega/issue-ops/issues/245#issuecomment-1588672334",
        "issue_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/245",
        "id": 1588672334,
        "node_id": "IC_kwDOJh34EM5esTdO",
        "user": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "created_at": "2023-06-13T07:05:56Z",
        "updated_at": "2023-06-13T07:05:56Z",
        "author_association": "NONE",
        "body": "## :vertical_traffic_light: org-get-webhook-delivery executed  GitHub Action Run ID: `5252323111`  [View Action Run](https://github.com/casa-vega/issue-ops/actions/runs/5252323111)",
        "reactions": {
          "url": "https://api.github.com/repos/casa-vega/issue-ops/issues/comments/1588672334/reactions",
          "total_count": 0,
          "+1": 0,
          "-1": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "performed_via_github_app": null
      },
      "repository": {
        "id": 639498256,
        "node_id": "R_kgDOJh34EA",
        "name": "issue-ops",
        "full_name": "casa-vega/issue-ops",
        "private": false,
        "owner": {
          "login": "casa-vega",
          "id": 80924672,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjgwOTI0Njcy",
          "avatar_url": "https://avatars.githubusercontent.com/u/80924672?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/casa-vega",
          "html_url": "https://github.com/casa-vega",
          "followers_url": "https://api.github.com/users/casa-vega/followers",
          "following_url": "https://api.github.com/users/casa-vega/following{/other_user}",
          "gists_url": "https://api.github.com/users/casa-vega/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/casa-vega/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/casa-vega/subscriptions",
          "organizations_url": "https://api.github.com/users/casa-vega/orgs",
          "repos_url": "https://api.github.com/users/casa-vega/repos",
          "events_url": "https://api.github.com/users/casa-vega/events{/privacy}",
          "received_events_url": "https://api.github.com/users/casa-vega/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/casa-vega/issue-ops",
        "description": "GitHub Issue Ops via Actions",
        "fork": false,
        "url": "https://api.github.com/repos/casa-vega/issue-ops",
        "forks_url": "https://api.github.com/repos/casa-vega/issue-ops/forks",
        "keys_url": "https://api.github.com/repos/casa-vega/issue-ops/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/casa-vega/issue-ops/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/casa-vega/issue-ops/teams",
        "hooks_url": "https://api.github.com/repos/casa-vega/issue-ops/hooks",
        "issue_events_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/events{/number}",
        "events_url": "https://api.github.com/repos/casa-vega/issue-ops/events",
        "assignees_url": "https://api.github.com/repos/casa-vega/issue-ops/assignees{/user}",
        "branches_url": "https://api.github.com/repos/casa-vega/issue-ops/branches{/branch}",
        "tags_url": "https://api.github.com/repos/casa-vega/issue-ops/tags",
        "blobs_url": "https://api.github.com/repos/casa-vega/issue-ops/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/casa-vega/issue-ops/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/casa-vega/issue-ops/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/casa-vega/issue-ops/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/casa-vega/issue-ops/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/casa-vega/issue-ops/languages",
        "stargazers_url": "https://api.github.com/repos/casa-vega/issue-ops/stargazers",
        "contributors_url": "https://api.github.com/repos/casa-vega/issue-ops/contributors",
        "subscribers_url": "https://api.github.com/repos/casa-vega/issue-ops/subscribers",
        "subscription_url": "https://api.github.com/repos/casa-vega/issue-ops/subscription",
        "commits_url": "https://api.github.com/repos/casa-vega/issue-ops/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/casa-vega/issue-ops/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/casa-vega/issue-ops/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/casa-vega/issue-ops/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/casa-vega/issue-ops/contents/{+path}",
        "compare_url": "https://api.github.com/repos/casa-vega/issue-ops/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/casa-vega/issue-ops/merges",
        "archive_url": "https://api.github.com/repos/casa-vega/issue-ops/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/casa-vega/issue-ops/downloads",
        "issues_url": "https://api.github.com/repos/casa-vega/issue-ops/issues{/number}",
        "pulls_url": "https://api.github.com/repos/casa-vega/issue-ops/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/casa-vega/issue-ops/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/casa-vega/issue-ops/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/casa-vega/issue-ops/labels{/name}",
        "releases_url": "https://api.github.com/repos/casa-vega/issue-ops/releases{/id}",
        "deployments_url": "https://api.github.com/repos/casa-vega/issue-ops/deployments",
        "created_at": "2023-05-11T15:16:01Z",
        "updated_at": "2023-06-07T03:56:59Z",
        "pushed_at": "2023-06-13T07:00:14Z",
        "git_url": "git://github.com/casa-vega/issue-ops.git",
        "ssh_url": "git@github.com:casa-vega/issue-ops.git",
        "clone_url": "https://github.com/casa-vega/issue-ops.git",
        "svn_url": "https://github.com/casa-vega/issue-ops",
        "homepage": "https://casa-vega.github.io/issue-ops/",
        "size": 188,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": true,
        "forks_count": 2,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "automation",
          "github-actions",
          "issue-ops"
        ],
        "visibility": "public",
        "forks": 2,
        "open_issues": 1,
        "watchers": 2,
        "default_branch": "main"
      },
      "organization": {
        "login": "casa-vega",
        "id": 80924672,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjgwOTI0Njcy",
        "url": "https://api.github.com/orgs/casa-vega",
        "repos_url": "https://api.github.com/orgs/casa-vega/repos",
        "events_url": "https://api.github.com/orgs/casa-vega/events",
        "hooks_url": "https://api.github.com/orgs/casa-vega/hooks",
        "issues_url": "https://api.github.com/orgs/casa-vega/issues",
        "members_url": "https://api.github.com/orgs/casa-vega/members{/member}",
        "public_members_url": "https://api.github.com/orgs/casa-vega/public_members{/member}",
        "avatar_url": "https://avatars.githubusercontent.com/u/80924672?v=4",
        "description": ""
      },
      "enterprise": {
        "id": 2,
        "slug": "avocado-corp",
        "name": "Avocado Corp.",
        "node_id": "MDEwOkVudGVycHJpc2Uy",
        "avatar_url": "https://avatars.githubusercontent.com/b/2?v=4",
        "description": "Makers of all the best avocado-based products.",
        "website_url": "https://github.com/enterprises/avocado-corp/",
        "html_url": "https://github.com/enterprises/avocado-corp",
        "created_at": "2018-04-06T02:42:55Z",
        "updated_at": "2022-09-29T12:24:24Z"
      },
      "sender": {
        "login": "github-actions[bot]",
        "id": 41898282,
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "html_url": "https://github.com/apps/github-actions",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
      }
    }
  },
  "response": {
    "headers": {
      "Content-Length": "166",
      "Content-Type": "text/html",
      "Date": "Tue, 13 Jun 2023 07:05:57 GMT",
      "Server": "nginx/1.18.0 (Ubuntu)"
    },
    "payload": "<html><head><title>502 Bad Gateway</title></head><body><center><h1>502 Bad Gateway</h1></center><hr><center>nginx/1.18.0 (Ubuntu)</center></body></html>"
  }
}
