github_instances:
  - instance: COM
    url: github.com
    organizations:
      - name: sfdc-demo
        owners:
          - cvega
          - owner2
      - name: org2
        owners:
          - owner3  
  - instance: EMU
    url: cvega-020f35ca452daa2a8.ghe-test.ninja
    organizations:
      - name: org2
        owners:
          - cvega
  - instance: SOMA
    url: https://github-instance-3.example.com
    organizations:
      - name: org3
        owners:
          - owner4
          - owner5
          - owner6
