name: archive a repository
inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  repository:
    description: "GitHub Repository"
    required: true

runs:
  using: composite
  steps:
    - name: archive a repository
      shell: bash
      run: |
        data=$(gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
          --input - <<< '{
            "archived": true
          }')
        if [[ $? -eq 0 ]]; then
          json_data=$(jq -nc '{ "msg": "created repository archive successfully", "status": "success" }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        else
          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create repository archive", "status": "error": $data }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        fi