name: "repo-create-workflow-from-template"
description: Description for "repo-create-workflow-from-template"

inputs:
  organization:
    required: true
  repository:
    required: true
  template:
    required: true
runs:
  using: composite
  steps:
    - name: Execute repo-create-workflow-from-template
      shell: bash
      run: |
        gh repo clone casa-vega/actions-template
        gh repo clone casa-vega/${{ inputs.repository }}

        cd ${{ inputs.repository }}

        git checkout -b ${{ inputs.organization }}-${{ inputs.repository }}-${{ inputs.template}}-template

        cp ../actions-template/${{ inputs.template }} .github/workflows/

        git add .github/workflows/${{ inputs.template }}
        git commit -m "Add ${{ inputs.template }} workflow"
        git push origin ${{ inputs.branch }}

        gh pr create --title "Add ${{ inputs.template }} workflow" --body "Add ${{ inputs.template }} workflow" --base main --head ${{ inputs.branch }}
