name: "repo-create-workflow-from-template"
description: Description for "repo-create-workflow-from-template"

inputs:
  organization:
    required: true
  repository:
    required: true
  template:
    required: true
runs:
  using: composite
  steps:
    - name: Execute repo-create-workflow-from-template
      shell: bash
      run: |
        gh repo clone casa-vega/action-template action-template
        gh repo clone casa-vega/${{ inputs.repository }}
        cd ${{ inputs.repository }}
        git checkout -b ${{ inputs.organization }}-${{ inputs.repository }}-${{ inputs.template}}-template
        mkdir -p .github/workflows
        cp ../action-template/${{ inputs.template }}.yml .github/workflows/
        git add .github/workflows/${{ inputs.template }}.yml
        git commit -m "Add ${{ inputs.template }} workflow"
        git push origin ${{ inputs.branch }}
        gh pr create \
          --title "Add ${{ inputs.template }} workflow template to ${{ inputs.repository }}" \
          --body "Add ${{ inputs.template }} workflow template to ${{ inputs.repository }}" \
          --base main \
          --head ${{ inputs.organization }}-${{ inputs.repository }}-${{ inputs.template}}-template
