name: deploy to paas
description: deploys your project
title: "[deploy-saas] deploy to paas environment"
labels:
  - deploy-to-saas
body:

  - type: markdown
    attributes:
      value: |
        ## Required changes

  - type: input
    id: project
    attributes:
      label: Project (*)
      description: the project of the PaaS platform
      placeholder: ex. example-project

  - type: input
    id: service
    attributes:
      label: Service (*)
      description: the service of the project in PaaS
      placeholder: ex. example-project

  - type: markdown
    attributes:
      value: |
        ## Option Changes

  - type: markdown
    attributes:
      value: |
        ### PaaS Configuration

  - type: dropdown
    id: platform
    attributes:
      label: platform
      description: Select a deploy platform
      options:
        - hydra
        - other

  - type: markdown
    attributes:
      value: |
        ## Standard Change Template Configuration

  - type: checkboxes
    id: std_change
    attributes:
      label: standard change
      description: Should a standard change template be used to enable auto-RFC creation.  
      options:
        - label: Enable

  - type: input
    id: chg_name
    attributes:
      label: change name
      description: The name of the change template
      placeholder: ex. Name_of_std_change

  - type: input
    id: chg_ci
    attributes:
      label: change ci
      description: The Change Templates Configuration Item (CI)
      placeholder: ex. Name_of_std_change

  - type: input
    id: chg_group
    attributes:
      label: change group
      description: The Change Templates Assignment Group
      placeholder: ex. Chg_group_name

  - type: input
    id: chg_email
    attributes:
      label: change email
      description: An email address that is a member of the Assignment Group for this change template
      placeholder: ex. email.addr@aexp.com

  - type: checkboxes
    id: manually_validate_ctask
    attributes:
      label: manually validate CTASK
      description: If enabled, requires manual closure of CTASK, otherwise auto-close validate CTASK after implementation complete. 
      options:
        - label: Enable

  - type: markdown
    attributes:
      value: |
        ## Deployment Configuration
           
  - type: checkboxes
    id: e3_automated
    attributes:
      label: e3 automated
      description: On push to default branch, auto deploy to E3 (Requires Standard Change Template Configuration section to be completed) 
      options:
        - label: Enable
        
  - type: checkboxes
    id: e2_automated
    attributes:
      label: e2 automated
      description: On push to default branch, auto deploy to E2 
      options:
        - label: Enable
        
  - type: checkboxes
    id: e1_on_pullrequest
    attributes:
      label: e1 on pull request
      description: On PR to default branch, auto deploy to E1 
      options:
        - label: Enable
        
    - type: markdown
    attributes:
      value: |
        ## Notification Configuration        
        
  - type: input
    id: slack_channel
    attributes:
      label: Slack channel notifications
      description: An email address that is a member of the Assignment Group for this change template
      placeholder: ex. C00000000    
        

  

        

