name: "[Enterprise] - create a github app"
description: creates a Github app project at the org level, must be approved by an enterprise admin
title: "[enterprise-github-app-request] Create a GitHub app at the org level"
labels:
  - enterprise-create-github-app
body:
# - type: dropdown
#   id: instance
#   attributes:
#     label: GitHub Instance (*)
#     description: The instance of Github you're targeting. 
#     options:
#       - COM
#       - EMU
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: name
    attributes:
      label: the name of the new github app (*)
      description: your new github app name
      placeholder: twilight-wizard
  