name: "[Organization] - get the status of a webhook"
description: allows users to get the status of a webhook
title: "[org-status-webhook] Get the Status of a webhook"
labels:
  - org-status-webhook
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance (*)
      description: The instance of Github you're targeting. 
      options:
        - COM
        - EMU
        - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: webhook_url
    attributes:
      label: Webhook URL (*)
      description: The webhook url
      placeholder: https://example.com/post
