name: "[Organization] - create a variable in an organization" 
description: add a variable to an organization
title: "[org-create-variable] Create a variable in an organization"
labels:
  - org-create-variable
body:
# - type: dropdown
#   id: instance
#   attributes:
#     label: GitHub Instance (*)
#     description: The instance of Github you're targeting. 
#     options:
#       - COM
#       - EMU
#       - SOMA
  - type: input
    id: organization
    attributes:
      label: organization
      description: GitHub Organization (*)
      placeholder: ex. github
  - type: input
    id: name
    attributes:
      label: variable name
      description: Variable name (*)
      placeholder: ex. U_ID
  - type: input
    id: value
    attributes:
      label: value
      description: Variable value (*)
      placeholder: ex. 123456789
  - type: dropdown
    id: visibility
    attributes:
      label: visibility (*)
      description: Description for visibility
      options:
        - all
        - private
        - selected
  - type: input
    id: repo_names
    attributes:
      label: repo_names (* if visibility is selected)
      description: If you choose selected, enter the repository name that can access the organization variable
      placeholder: ex. value
