name:  "[Organization] - list team maintainers"
description: allows users to list orgnization team maintainers
title: "[org-team-maintainer-list] List organization team maintainers"
labels:
  - org-get-team-maintainers-list
body:
# - type: dropdown
#   id: instance
#   attributes:
#     label: GitHub Instance (*)
#     description: The instance of Github you're targeting. 
#     options:
#       - COM
#       - EMU
#       - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
