name: create an organization secret
description: creates a secret for your organization
title: "[org-secret] Create a new organization secret"
labels:
  - org-secret-create
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance (*)
      description: The instance of Github you are targeting. 
      options:
        - COM
        - EMU
        - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. salesforce
  - type: input
    id: secret_name
    attributes:
      label: Secret Name (*)
      description: The name of the secret
      placeholder: ex. my-secret
  - type: input
    id: secret_value
    attributes:
      label: Secret Value (*)
      description: The value of the secret
      placeholder: ex. my-secret-value