name: "[Organization] - create a github app"
description: creates a Github app project at the org level, must be approved by an enterprise admin
title: "[org-github-app-request] Create a GitHub app at the org level"
labels:
  - org-create-github-app
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance (*)
      description: The instance of Github you're targeting. 
      options:
        - COM
        - EMU
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: name
    attributes:
      label: the name of the new organization (*)
      description: your new fancy/descriptive organization name
      placeholder: fuschia-sailfish
  