name: "[Organization] - delete a webhook"
description: deletes a unique organization webhook
title: "[org-webhook-delete] Delete and organization webhook"
labels:
  - org-delete-webhook
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance (*)
      description: The instance of Github you are targeting. 
      options:
        - COM
        - EMU
        - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. salesforce
  - type: input
    id: webhook_url
    attributes:
      label: Webhook URL (*)
      description: The webhook url
      placeholder: https://example.com/post
