name: "[Organization] - create a v2 project" 
description: creates a Github v2 project at the org level
title: "[project-create] Create a v2 project"
labels:
  - org-create-projectv2
body:
# - type: dropdown
#   id: instance
#   attributes:
#     label: GitHub Instance (*)
#     description: The instance of Github you're targeting. 
#     options:
#       - COM
#       - EMU
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: name
    attributes:
      label: the new name of the project (*)
      description: your new fancy/descriptive project name
      placeholder: fuschia-sailfish
  