name: create a v2 project 
description: creates a v2 project
title: "[project-create] Rename a repository"
labels:
  - project-create
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance (*)
      description: The instance of Github you're targeting. 
      options:
        - COM
        - EMU
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: name
    attributes:
      label: the new name of the project (*)
      description: your new fancy/descriptive project name
      placeholder: fuschia-sailfish
  