name: archive a repository
description: set a repo to archived making it read only
title: "[repo-archive] Archive a repository"
labels:
  - repo-archive
body:
  - type: dropdown
    id: instance
    attributes:
      label: GitHub Instance (*)
      description: The instance of Github you're targeting. 
      options:
        - COM
        - EMU
        - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: repository
    attributes:
      label: GitHub Repository (*)
      description: The name of the github repository (must be exact)
      placeholder: ex. actions
