name: "[Repo] - update the repository name" 
description: renames an existing repository
title: "[repo-update-name] Rename a repository"
labels:
  - repo-update-name
body:
# - type: dropdown
#   id: instance
#   attributes:
#     label: GitHub Instance (*)
#     description: The instance of Github you're targeting. 
#     options:
#       - COM
#       - EMU
#       - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. github
  - type: input
    id: repository
    attributes:
      label: GitHub Repository (*)
      description: The name of the github repository to create
      placeholder: ex. purple-fish
  - type: input
    id: name
    attributes:
      label: the new name of the repository (*)
      description: your new fancy/descriptive repository name
      placeholder: fuschia-sailfish
  