name: "[Repo] - Create a branch protection rule."
description: Create a branch protection rule for a repository.
title: "[repo-create-branch-protection] Create a branch protection rule."
labels:
  - repo-create-branch-protection
body:
  # - type: input
  #   id: instance
  #   attributes:
  #     label: instance (*)
  #     description: Description for instance
  #     placeholder: ex. value
  - type: input
    id: organization
    attributes:
      label: Organization (*)
      description: The account owner of the repository. The name is not case sensitive.
      placeholder: ex. github
  - type: input
    id: repository
    attributes:
      label: Repository (*)
      description: The name of the repository without the .git extension. The name is not case sensitive.
      placeholder: ex. octocat
  - type: input
    id: branch
    attributes:
      label: Branch (*)
      description: The name of the branch. Cannot contain wildcard characters.
      placeholder: ex. main
  - type: input
    id: required_status_checks
    attributes:
      label: Required status checks
      description: Require status checks to pass before merging.
      placeholder: ex. continuous-integration/gh-actions
  - type: checkboxes
    id: enforce_admins
    attributes:
      label: Enforce admins
      description: Description for enforce_admins
      options:
        - label: Enable
  - type: input
    id: required_pull_request_reviews
    attributes:
      label: Required pull request reviews
      description: Description for required_pull_request_reviews
      placeholder: ex. value
  - type: input
    id: restrictions
    attributes:
      label: Restrictions
      description: Description for restrictions
      placeholder: ex. value
  - type: checkboxes
    id: required_linear_history
    attributes:
      label: Required linear history
      description: Description for required_linear_history
      options:
        - label: Enable
  - type: checkboxes
    id: allow_force_pushes
    attributes:
      label: Allow force pushes
      description: Description for allow_force_pushes
      options:
        - label: Enable
  - type: checkboxes
    id: allow_deletions
    attributes:
      label: Allow deletions
      description: Description for allow_deletions
      options:
        - label: Enable
  - type: checkboxes
    id: Required_conversation_resolution
    attributes:
      label: required_conversation_resolution
      description: Description for required_conversation_resolution
      options:
        - label: Enable
  - type: checkboxes
    id: lock_branch
    attributes:
      label: Lock branch
      description: Description for lock_branch
      options:
        - label: Enable
  - type: checkboxes
    id: allow_fork_syncing
    attributes:
      label: Allow fork syncing
      description: Description for allow_fork_syncing
      options:
        - label: Enable
