name: "[Repo] - delete a webhook"
description: deletes a unique repository webhook
title: "[repo-delete-webhook] Delete an organization webhook"
labels:
  - repo-delete-webhook
body:
# - type: dropdown
#   id: instance
#   attributes:
#     label: GitHub Instance (*)
#     description: The instance of Github you are targeting. 
#     options:
#       - COM
#       - EMU
#       - SOMA
  - type: input
    id: organization
    attributes:
      label: GitHub Organization (*)
      description: The name of the github organization (must be exact)
      placeholder: ex. salesforce
  - type: input
    id: repository
    attributes:
      label: GitHub Repository (*)
      description: The name of the github repository to create
      placeholder: ex. other-fuchsia-sailfish
  - type: input
    id: webhook_url
    attributes:
      label: Webhook URL (*)
      description: The webhook url
      placeholder: https://example.com/post