name: "[Repo] - Create a branch protection rule."
description: Create a branch protection rule for a repository.
title: "[repo-create-branch-protection] Create a branch protection rule."
labels:
  - repo-create-branch-protection
body:
  # - type: input
  #   id: instance
  #   attributes:
  #     label: instance (*)
  #     description: Description for instance
  #     placeholder: ex. value
  - type: input
    id: organization
    attributes:
      label: Organization (*)
      description: The account owner of the repository. The name is not case sensitive.
      placeholder: ex. github
  - type: input
    id: repository
    attributes:
      label: Repository (*)
      description: The name of the repository without the .git extension. The name is not case sensitive.
      placeholder: ex. octocat
  - type: input
    id: branch
    attributes:
      label: Branch (*)
      description: The name of the branch. Cannot contain wildcard characters.
      placeholder: ex. main
  - type: input
    id: required_status_checks
    attributes:
      label: Required status checks
      description: Require status checks to pass before merging.
      placeholder: ex. continuous-integration/gh-actions
  - type: checkboxes
    id: enforce_admins
    attributes:
      label: Enforce admins
      description: Enforce all configured restrictions for administrators
      options:
        - label: Enable
  - type: markdown
    attributes:
      value: |
        ---
        ## Required pull request reviews
  - type: input
    id: required_pull_request_reviews
    attributes:
      label: Required pull request reviews
      description: Require at least one approving review on a pull request, before merging.
      placeholder: ex. value
  - type: input
    id: restrictions
    attributes:
      label: Restrictions
      description: Restrict who can push to the protected branch
      placeholder: ex. value
  - type: checkboxes
    id: required_linear_history
    attributes:
      label: Required linear history
      description: Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch
      options:
        - label: Enable
  - type: checkboxes
    id: allow_force_pushes
    attributes:
      label: Allow force pushes
      description: Permits force pushes to the protected branch by anyone with write access to the repository.
      options:
        - label: Enable
  - type: checkboxes
    id: allow_deletions
    attributes:
      label: Allow deletions
      description: Allows deletion of the protected branch by anyone with write access to the repository
      options:
        - label: Enable
  - type: checkboxes
    id: Required_conversation_resolution
    attributes:
      label: required_conversation_resolution
      description: Requires all conversations on code to be resolved before a pull request can be merged into a branch that matches this rule
      options:
        - label: Enable
  - type: checkboxes
    id: lock_branch
    attributes:
      label: Lock branch
      description: Whether to set the branch as read-only
      options:
        - label: Enable
  - type: checkboxes
    id: allow_fork_syncing
    attributes:
      label: Allow fork syncing
      description: Whether users can pull changes from upstream when the branch is locked.
      options:
        - label: Enable
