name: "[Repo] - Create a workflow from template"
description: create an action workflow from pr and add it to your repo
title: "[repo-create-workflow-from-template] Create a workflow from template"
labels:
  - repo-create-workflow-from-template
body:
  - type: input
    id: organization
    attributes:
      label: organization (*)
      description: The org your repo lives in
      placeholder: ex. value
  - type: input
    id: repository
    attributes:
      label: GitHub Repository (*)
      description: The name of the github repository (must be exact)
      placeholder: ex. super-awesome-repo
  - type: dropdown
    id: template
    attributes:
      label: Workflow Template (*)
      description: The Github Actions template you're targeting. 
      options:
        - python
        - ruby
        - java
