name: set announcement banner
description: create an organization announcement banner

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  announcement:
    description: "The announcement text"
    required: true
  expires_at:
    description: "The announcement expiration date in `YYYY-MM-DD` format"
    required: true
  user_dismissible:
    description: "Allow user to dismiss banner?"
    required: true


runs:
  using: composite
  steps:
    - name: archi
      shell: bash
      run: |
        gh api \
        --method PATCH \
          orgs/${{ inputs.organization }}/announcement \
          --input - <<< '{
            "announcement": ${{ inputs.announcement }},
            "expires_at": ${{ inputs.expires_at }},
            "user_dismissible": ${{ inputs.user_dismissible }}
          }'
