name: update a repository name

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  repository:
    description: "GitHub Repository"
    required: true
  name:
    description: "GitHub Repository Name"
    required: true

runs:
  using: composite
  steps:
    - name: update a repository name
      shell: bash
      run: |
        data=$(gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
          --method PATCH \
          -f "name=${{ inputs.name }}")
        if [[ $? -eq 0 ]]; then
          json_data=$(jq -nc '{ "msg": "updated repository name successfully", "status": "success" }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        else
          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to rename repository", "status": "error": $data }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        fi