name: create organization webhook
author: "@cvega"
description: create organization webhook

inputs:
  instance:
    description: "GitHub Instance"
    required: true
    type: string
  organization:
    description: "GitHub Organization"
    required: true
    type: string
  payload_url:
    description: "Payload URL"
    required: true
    type: string
  content_type:
    description: "Content Type"
    required: true
    type: string
  active:
    description: "Activate Webhook"
    required: true
    default: false
  events:
    description: "Webhook Events"
    required: true
    type: string
  host:
    description: "GitHub Host"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: login with gh cli
      run: |
        echo ${{ secrets[format('{0}_TOKEN', inputs.instance)] }} > token.txt
        gh auth login \
        --hostname ${{ inputs.host }} \
        --with-token < token.txt
        rm token.txt

    - name: create an organization webhook
      run: |
        active="$([[ "${{ inputs.active }}" == "Enable" ]] && echo true || echo false)"
        events="$(echo "${{ inputs.events }}" | jq -Rc 'split(",")')"
        gh api orgs/${{ inputs.organization }}/hooks \
          --input - <<< '{
            "name": "web",
            "active": '$(echo $active)',
            "events": '$(echo $events)',
            "config": {
              "url": "${{ inputs.payload_url }}",
              "content_type": "${{ inputs.content_type }}"
            }
          }'
    