name: create an organization webhook

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  webhook_url:
    description: "Webhook URL"
    required: true
  content_type:
    description: "Content Type"
    required: true
  active:
    description: "Activate Webhook"
    required: true
  events:
    description: "Webhook Events"
    required: true
  hostname:
    description: "GitHub Host"
    required: true
  secret:
    description: "secret"
    required: false

runs:
  using: composite
  steps:
    - name: create an organization webhook
      shell: bash
      run: |
        active="$([[ "${{ inputs.active }}" == "["Enable"]" ]] && echo true || echo false)"
        data=$(gh api orgs/${{ inputs.organization }}/hooks \
          --input - << EOF
            {
              "name": "web",
              "active": $active,
              "events": ${{ inputs.events }},
              "config": {
                "url": "${{ inputs.webhook_url }}",
                "content_type": "${{ inputs.content_type }}"
              }
            }
          EOF
        )
        if [[ $? -eq 0 ]]; then
          json_data=$(jq -nc '{ "msg": "created organization webhook successfully", "status": "success" }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        else
          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create organization webhook", "status": "error": $data }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        fi