name: toggle repository visibility

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  repository:
    description: "GitHub Repository"
    required: true
  visibility:
    description: "GitHub Repository Visibility (private/internal)"
    required: true

runs:
  using: composite
  steps:
    - name: toggle repository visibility
      shell: bash
      run: |
        data=$(gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
          --method PATCH \
          -f "visibility=${{ inputs.visibility }}")
        if [[ $? -eq 0 ]]; then
          json_data=$(jq -nc '{ "msg": "repository visability toggled successfully", "status": "success" }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        else
          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to toggle repository visibility", "status": "error": $data }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        fi