name: create a new organization
description: request to create a new organization

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true


runs:
  using: composite
  steps:
    - name: create a new github organization
      shell: bash
      run: |
        # GUS API code goes here

