name: create a project
description: create a v2 project

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  name:
    description: "GitHub Project Name"
    required: true

runs:
  using: composite
  steps:
    - name: create a v2 project
      shell: bash
      run: |
        oid=$(gh api /users/${{ inputs.organization }} | jq -r '.node_id')
        query="mutation{
          createProjectV2(
            input: {
              ownerId: \"$oid\",
              title: \"${{ inputs.name }}\",
            }
          ){
            projectV2 {
              id
            }
          }
        }"
        gh api graphql -f query="$query"

