name: update labels

on:
  push:
    paths:
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup gh cli
        shell: bash
        run: |
          echo ${{ secrets.emu_issue_ops }} > token.txt
          gh auth login \
            --hostname github.com \
            --with-token < token.txt
          rm token.txt
      - name: compare and generate new labels
        shell: bash
        run: |
          ./.github/scripts/generate_labels.sh ${{ github.repository }}
