name: org-create-announcement

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  announcement:
    description: "The announcement text"
    required: true
  expires_at:
    description: "The announcement expiration date in `YYYY-MM-DD` format"
    required: true
  user_dismissible:
    description: "Allow user to dismiss banner?"
    required: true

runs:
  using: composite
  steps:
    - name: create a new github organization announcement
      shell: bash
      run: |
        echo -e "DISMISSIBLE=$([[ "${{ inputs.user_dismissible }}" == "["Enable"]" ]] && echo true || echo false)" >> $GITHUB_ENV
        data=$(gh api \
          --method PATCH \
          orgs/${{ inputs.organization }}/announcement \
          --input - <<< '{
            "announcement": "${{ inputs.announcement }}",
            "expires_at": "${{ inputs.expires_at }}T00:00:00.000+00:00",
            "user_dismissible": ${{ env.DISMISSIBLE }}
          }'
        )
        if [[ $? -eq 0 ]]; then
          json_data=$(jq -nc '{ "msg": "annoucement created successfully", "status": "success" }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        else
          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create announcement", "status": "error": $data }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        fi
