name: org-create-announcement

inputs:
  instance:
    description: "GitHub Instance"
    required: true
  organization:
    description: "GitHub Organization"
    required: true
  announcement:
    description: "The announcement text"
    required: true
  expires_at:
    description: "The announcement expiration date in `YYYY-MM-DD` format"
    required: true
  user_dismissible:
    description: "Allow user to dismiss banner?"
    required: true

runs:
  using: composite
  steps:
    - name: create a new github organization announcement
      shell: bash
      run: |
        dismissible=true
        [ "${{ inputs.user_dismissible }}" == '["Enable"]' ] && dismissible=true || dismissible=false
        data=$(gh api orgs/casa-vega/announcement \
          --method PATCH \
          -f "announcement=${{ inputs.announcement }}" \
          -f "expires_at=${{ inputs.expires_at }}T00:00:00" \
          -F "user_dismissible=$dismissible")
        if [[ $? -eq 0 ]]; then
          json_data=$(jq -nc '{ "msg": "announcement created successfully", "status": "success" }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        else
          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create announcement", "status": "failure", "error": $data }')
          echo -e "RESULT=$json_data" >> $GITHUB_ENV
        fi
